aristek_jsonapi:
    provider_key: main
    user_class: App\Entity\User
    user_repository: App\Repository\UserRepository
    allow_aristek_mailer: true
    user_service_id: App\Service\UserService
    filesystem_adapters:
        local: { type: local }
    filesystem_mappings:
        user_avatar_file:
            entity_class_name: App\Entity\User
            property: avatar
            path: '%kernel.project_dir%/var/uploads/user/avatars'
            filesystem_adapter: local
            route: { name: 'users_avatar' }
            allowed_mime_types:
                - 'image/png'
                - 'image/jpeg'
            allowed_extensions:
                - 'png'
                - 'jpeg'
                - 'jpg'
