aristek_jsonapi:
    provider_key: main
    user_class: App\Entity\User
    user_repository: App\Repository\UserRepository
    allow_aristek_mailer: true
    user_service_id: App\Service\UserService
    filesystem_adapters:
        local: { type: local }
    filesystem_mappings:
        user_avatar_file:
            entity_class_name: App\Entity\User
            property: avatar
            path: '%kernel.project_dir%/var/uploads/user/avatars'
            filesystem_adapter: local
            route: { name: 'users_avatar' }
            allowed_mime_types:
                - 'image/png'
                - 'image/jpeg'
            allowed_extensions:
                - 'png'
                - 'jpeg'
                - 'jpg'

    resources:
        contacts:
            data_type: App\Entity\Contact
            transformer: App\Transformer\ContactTransformer

        departments:
            data_type: App\Entity\Department
            transformer: App\Transformer\DepartmentTransformer

        profiles:
            data_type: App\Entity\Profile
            transformer:
                attributes: ['firstName', 'lastName', 'birthDay']
                relationships: ['contacts']

        userRoles:
            data_type: App\Entity\UserRole
            transformer: App\Transformer\UserRoleTransformer

        users:
            data_type: App\Entity\User
            transformer:
                attributes: ['active', 'avatar', 'email', 'username', 'profile']
                relationships: ['departments', 'userRoles']
