json_api_resour—Åe:
    resource: '../src/Controller/Resource'
    type: annotation
    prefix: '/resources'
    options:
        aristek: true

#index:
#    path: /
#    controller: App\Controller\DefaultController::index
